module.exports={
    google:{
        clientID:'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        clientSecret:'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    },
    mongodb:{
        dbURI:'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    },
    session:{
        cookiekey:'xxxxxxxxxxxxxxxxxxxxxxxxxx'
    }
}